//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SPKCFManagement.DB.MySQL.spkcms
{

    [Persistent(@"branch")]
    public partial class BranchModel : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>("id", ref fid, value); }
        }
        string fnama;
        [Size(255)]
        public string nama
        {
            get { return fnama; }
            set { SetPropertyValue<string>("nama", ref fnama, value); }
        }
        string falamat;
        [Size(255)]
        public string alamat
        {
            get { return falamat; }
            set { SetPropertyValue<string>("alamat", ref falamat, value); }
        }
        string fno_telepon;
        [Size(45)]
        public string no_telepon
        {
            get { return fno_telepon; }
            set { SetPropertyValue<string>("no_telepon", ref fno_telepon, value); }
        }
        DateTime fcreated_at;
        public DateTime created_at
        {
            get { return fcreated_at; }
            set { SetPropertyValue<DateTime>("created_at", ref fcreated_at, value); }
        }
        DateTime fupdated_at;
        public DateTime updated_at
        {
            get { return fupdated_at; }
            set { SetPropertyValue<DateTime>("updated_at", ref fupdated_at, value); }
        }
        string fcreated_by;
        [Size(45)]
        public string created_by
        {
            get { return fcreated_by; }
            set { SetPropertyValue<string>("created_by", ref fcreated_by, value); }
        }
        string fupdated_by;
        [Size(45)]
        public string updated_by
        {
            get { return fupdated_by; }
            set { SetPropertyValue<string>("updated_by", ref fupdated_by, value); }
        }
    }

}
