//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SPKCFManagement.DB.MySQL.spkcms
{

    [Persistent(@"pelunasan")]
    public partial class PelunasanModel : XPLiteObject
    {
        long fid;
        [Key(true)]
        public long id
        {
            get { return fid; }
            set { SetPropertyValue<long>("id", ref fid, value); }
        }
        string fno_spk;
        [Size(255)]
        public string no_spk
        {
            get { return fno_spk; }
            set { SetPropertyValue<string>("no_spk", ref fno_spk, value); }
        }
        string fnama_pembayar;
        [Size(255)]
        public string nama_pembayar
        {
            get { return fnama_pembayar; }
            set { SetPropertyValue<string>("nama_pembayar", ref fnama_pembayar, value); }
        }
        decimal fjumlah;
        public decimal jumlah
        {
            get { return fjumlah; }
            set { SetPropertyValue<decimal>("jumlah", ref fjumlah, value); }
        }
    }

}
