//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SPKCFManagement.DB.MySQL.spkcms
{

    [Persistent(@"permission")]
    public partial class PermissionModel : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>("id", ref fid, value); }
        }
        string fpermission_name;
        [Size(45)]
        public string permission_name
        {
            get { return fpermission_name; }
            set { SetPropertyValue<string>("permission_name", ref fpermission_name, value); }
        }
        int fpermission_type;
        public int permission_type
        {
            get { return fpermission_type; }
            set { SetPropertyValue<int>("permission_type", ref fpermission_type, value); }
        }
        string fpermission_code;
        [Size(11)]
        public string permission_code
        {
            get { return fpermission_code; }
            set { SetPropertyValue<string>("permission_code", ref fpermission_code, value); }
        }
        int fparent;
        public int parent
        {
            get { return fparent; }
            set { SetPropertyValue<int>("parent", ref fparent, value); }
        }
    }

}
