//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SPKCFManagement.DB.MySQL.spkcms
{

    [Persistent(@"role_has_permission")]
    public partial class RoleHasPermissionModel : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>("id", ref fid, value); }
        }
        int fpermissionid;
        public int permissionid
        {
            get { return fpermissionid; }
            set { SetPropertyValue<int>("permissionid", ref fpermissionid, value); }
        }
        int froleid;
        public int roleid
        {
            get { return froleid; }
            set { SetPropertyValue<int>("roleid", ref froleid, value); }
        }
    }

}
