//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SPKCFManagement.DB.MySQL.spkcms
{

    [Persistent(@"sales_head")]
    public partial class SalesHeadModel : XPLiteObject
    {
        int fkode_sh;
        [Key]
        public int kode_sh
        {
            get { return fkode_sh; }
            set { SetPropertyValue<int>("kode_sh", ref fkode_sh, value); }
        }
        string fnama_sh;
        [Size(255)]
        public string nama_sh
        {
            get { return fnama_sh; }
            set { SetPropertyValue<string>("nama_sh", ref fnama_sh, value); }
        }
        int fbranchid;
        public int branchid
        {
            get { return fbranchid; }
            set { SetPropertyValue<int>("branchid", ref fbranchid, value); }
        }
    }

}
