//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SPKCFManagement.DB.MySQL.spkcms
{

    [Persistent(@"sales_view")]
    public partial class SalesViewModel : XPLiteObject
    {
        int fkode_sales;
        [Key]
        public int kode_sales
        {
            get { return fkode_sales; }
            set { SetPropertyValue<int>("kode_sales", ref fkode_sales, value); }
        }
        string fnama_sales;
        [Size(255)]
        public string nama_sales
        {
            get { return fnama_sales; }
            set { SetPropertyValue<string>("nama_sales", ref fnama_sales, value); }
        }
        string fnama_sh;
        [Size(255)]
        public string nama_sh
        {
            get { return fnama_sh; }
            set { SetPropertyValue<string>("nama_sh", ref fnama_sh, value); }
        }
        int fshbranch;
        public int shbranch
        {
            get { return fshbranch; }
            set { SetPropertyValue<int>("shbranch", ref fshbranch, value); }
        }
        int fsalesbranch;
        public int salesbranch
        {
            get { return fsalesbranch; }
            set { SetPropertyValue<int>("salesbranch", ref fsalesbranch, value); }
        }
        int fkode_sh;
        public int kode_sh
        {
            get { return fkode_sh; }
            set { SetPropertyValue<int>("kode_sh", ref fkode_sh, value); }
        }
    }

}
