//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SPKCFManagement.DB.MySQL.spkcms
{

    [Persistent(@"spk")]
    public partial class SpkModel : XPLiteObject
    {
        string fno_spk;
        [Key]
        [Size(255)]
        public string no_spk
        {
            get { return fno_spk; }
            set { SetPropertyValue<string>("no_spk", ref fno_spk, value); }
        }
        int fkode_sales;
        public int kode_sales
        {
            get { return fkode_sales; }
            set { SetPropertyValue<int>("kode_sales", ref fkode_sales, value); }
        }
        int fkode_sh;
        public int kode_sh
        {
            get { return fkode_sh; }
            set { SetPropertyValue<int>("kode_sh", ref fkode_sh, value); }
        }
        string fnama_customer;
        [Size(255)]
        public string nama_customer
        {
            get { return fnama_customer; }
            set { SetPropertyValue<string>("nama_customer", ref fnama_customer, value); }
        }
        string falamat;
        [Size(255)]
        public string alamat
        {
            get { return falamat; }
            set { SetPropertyValue<string>("alamat", ref falamat, value); }
        }
        string ftelepon;
        [Size(255)]
        public string telepon
        {
            get { return ftelepon; }
            set { SetPropertyValue<string>("telepon", ref ftelepon, value); }
        }
        string fjenis_kendaraan;
        [Size(255)]
        public string jenis_kendaraan
        {
            get { return fjenis_kendaraan; }
            set { SetPropertyValue<string>("jenis_kendaraan", ref fjenis_kendaraan, value); }
        }
        string fwarna_kendaraan;
        [Size(255)]
        public string warna_kendaraan
        {
            get { return fwarna_kendaraan; }
            set { SetPropertyValue<string>("warna_kendaraan", ref fwarna_kendaraan, value); }
        }
        string fstatus_spk;
        [Size(255)]
        public string status_spk
        {
            get { return fstatus_spk; }
            set { SetPropertyValue<string>("status_spk", ref fstatus_spk, value); }
        }
        DateTime ftanggal_spk;
        public DateTime tanggal_spk
        {
            get { return ftanggal_spk; }
            set { SetPropertyValue<DateTime>("tanggal_spk", ref ftanggal_spk, value); }
        }
    }

}
