//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SPKCFManagement.DB.MySQL.spkcms
{

    [Persistent(@"user")]
    public partial class UserModel : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>("id", ref fid, value); }
        }
        string fname;
        [Size(45)]
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>("name", ref fname, value); }
        }
        string femail;
        [Size(45)]
        public string email
        {
            get { return femail; }
            set { SetPropertyValue<string>("email", ref femail, value); }
        }
        string fpassword;
        [Size(45)]
        public string password
        {
            get { return fpassword; }
            set { SetPropertyValue<string>("password", ref fpassword, value); }
        }
        int fbranchid;
        public int branchid
        {
            get { return fbranchid; }
            set { SetPropertyValue<int>("branchid", ref fbranchid, value); }
        }
        bool fisactive;
        public bool isactive
        {
            get { return fisactive; }
            set { SetPropertyValue<bool>("isactive", ref fisactive, value); }
        }
    }

}
