//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SPKCFManagement.DB.MySQL.spkcms
{

    [Persistent(@"userview")]
    public partial class UserviewModel : XPLiteObject
    {
        int fid;
        [Key]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>("id", ref fid, value); }
        }
        string fusername;
        [Size(45)]
        public string username
        {
            get { return fusername; }
            set { SetPropertyValue<string>("username", ref fusername, value); }
        }
        string femail;
        [Size(45)]
        public string email
        {
            get { return femail; }
            set { SetPropertyValue<string>("email", ref femail, value); }
        }
        bool fisactive;
        public bool isactive
        {
            get { return fisactive; }
            set { SetPropertyValue<bool>("isactive", ref fisactive, value); }
        }
        string fnama_cabang;
        [Size(255)]
        public string nama_cabang
        {
            get { return fnama_cabang; }
            set { SetPropertyValue<string>("nama_cabang", ref fnama_cabang, value); }
        }
    }

}
